package Exceptions_3;

public class Exception_Example0 {
public static void main(String[] args) {
		int val1 = 20;

		System.out.println("Execution Started");

		int val2 = val1/0;

		System.out.println("Value of value2 is"+val2);

		System.out.println("Execution Ended");
	}
}

// you should expect an error - this code is expanded as try catch and finally key words are used to

// to explain the use of these key words in the next tabs


